### ISSUE TITLE
mouse-over thumbnails is covered

### ISSUE THREAD

**Issue by sorakirahk** [dnsev-h/x#1]
if num of galleries fewer than 7, the infinite scroll page header will cover the mouse-over thumbnails
![Sora_2019-05-27_18-45-35](https://user-images.githubusercontent.com/24854146/58414988-a35e2900-80af-11e9-9552-aab45597f6b1.png)

**Comment by dnsev-h** [comment]
Fixed in [v1.1.1](https://github.com/dnsev-h/x/commit/4dd506a6acf172cbef7d0524b7896047354e2a9d)
