### ISSUE TITLE
infinite scroll slightly broken

### ISSUE THREAD

**Issue by Yoposoc** [dnsev-h/x#17]
The newly generated page on gallery view repeats a large number of galleries.

**Comment by DestroyTargetNonBasicLand** [comment]
Use this userscript instead: https://github.com/FlandreDaisuki/My-Browser-Extensions/blob/master/userscripts/UnlockHathPerks.user.js
![Screenshot 2021-03-25 133014](https://user-images.githubusercontent.com/36361031/112480838-519b8e00-8d6e-11eb-9818-6db03810f026.png)

**Comment by Yoposoc** [comment]
very cool, thanks.
