### ISSUE TITLE
infinite scroll broken on new layout

### ISSUE THREAD

**Issue by fullmetal1** [dnsev-h/x#26]
Seems like they changed the website and broke infinite scrolling

**Comment by mbahArip** [comment]
If you're using e-hentai, you can toggle Gallery Page Numbering to yes at settings page.
Sadly it's not working on exh.
![image](https://user-images.githubusercontent.com/62494292/199782566-a35b9a42-d5e9-426c-8cde-ede0a94aedc1.png)

**Comment by dnsev-h** [comment]
Should be fixed in [v1.1.8](https://github.com/dnsev-h/x/commit/54d37ca3d7f9111d7bc85b1c0a3d2857c93dfbca).
