### ISSUE TITLE
What do these scripts exactly do?

### ISSUE THREAD

**Issue by Yoposoc** [dnsev-h/x#3]
What do these scripts exactly do? Some of them, I can't figure out what behavior they do when I switch them on, especially the "favorites" and "Gallery Info Copy".

**Comment by dnsev-h** [comment]
I should put descriptions up for them all at some point.

"Favorites" adds a favorite link to the gallery image viewer at the bottom of the page. I may expand upon this extension at some point, hence the generic name.

"Gallery Info Copy" adds buttons next to the gallery titles which copy the title when clicked. This was a request someone had for a script.

**Comment by Yoposoc** [comment]
Wow, they're so subtle I didn't notice. But I like how unintrusive it is, thanks.
