### ISSUE TITLE
Custom search links doesn't work well with galleries with secondary titles

### ISSUE THREAD

**Issue by LitDub** [dnsev-h/x#6]
Galleries that use "Title | Second Title " as their naming structure sometimes turn up few results when using "search by name" because other translations of the gallery only use the first title.

Would you consider adding an option to search for _only_ the first title?

**Comment by dnsev-h** [comment]
`{short-name1}` and `{short-name2}` can now be used to specify whether you want the part before the bar or after the bar; 1 is before, 2 is after. If there is no bar, both values will default to `{short-name}`.
